### PR TITLE
fix(webapp): fix little bugs

### LINKED ISSUE #863: Add to vote button wont load i18n
Screen Shot 2021-11-22 at 09 58 36

### LINKED ISSUE #864: Buttons dont execute actions
- image

- image

- image

- image

### LINKED ISSUE #865: Social media link in footer homepage is bad

### PR DESCRIPTION
**Pull request by AngeloCG97**
## Add to vote button wont load i18n

Resolve #865
Resolve #864
Resolve #863

### CODE REVIEW

File: contracts/rateproducer/include/rateproducer.hpp [hunk 1]
```diff
@@ -44,7 +44,7 @@ using eosio::public_key;
 */
 namespace eosio {
     constexpr name system_account{"eosio"_n};
-    constexpr name eden_account{"genesisdeden"_n};
+    constexpr name eden_account{"genesis.eden"_n};
```
Comment (xavier506) [inline contracts/rateproducer/include/rateproducer.hpp:47]: @AngeloCG97 Is this change supposed to be imported

**Review by xavier506 — APPROVED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM
