### PR TITLE
Fix general bugs and add new feature

### LINKED ISSUE #602: Add links to other BP scorecard factors
The subjective opinions of eden members will be combined with objective metrics to determine which BPS will be voted f0r by the eden proxy 

From eden members proxy group telegram : https://t.me/eos_bp_scoreboard

> The more objective KPI will be provided by various community sources. The final weighting of each respective metric is TBD. The plan will be to have a focused call with various Eden community members with BP experience to help finalize this weighting system. A few community data sources are as follows:

**EOS Nation Scorecard:**
https://validate.eosnation.io/eos/producers/

**Aloha EOS BP Research Portal and Benchmarks:**
https://www.alohaeos.com/tools

There should be links to these third party tools from eos rate

### LINKED ISSUE #667: Embed link to BP Spotlight Youtube video
Embed link to the BP Spotlight Youtube video in the BP profile page. 

Sample link:  https://youtu.be/vKqzzc_qSIg

### LINKED ISSUE #728: General Ratings label
Change EOS Rating for General Rating

image

### LINKED ISSUE #731: Link logo to block producers
the logo should link to block producers route

image

### LINKED ISSUE #737: Remove rating not function

### PR DESCRIPTION
**Pull request by AngeloCG97**
## Remove rating not function

Resolve #602
Resolve  #731
Resolve  #667
Resolve  #728
Resolve #737

### What does this PR have?

1. Add new data for bps
1. Change ref to eosrate logo
1. Show ede interview and scorecard Factors links
2. Fix remove rating not function
3. Change texts

### CODE REVIEW

File: hapi/src/libs/add-bps-info.js [hunk 1]
```diff
@@ -1,391 +1,560 @@
...
     }
   },
-];
+  {
+    owner: 'atticlabjbpn',
+    general_info: {
+      websiteText:
+        'Duis diam orci, vehicula non bibendum non, interdum ac neque. Fusce cursus arcu quis ligula accumsan ultrices. Pellentesque rutrum, libero vitae tincidunt lobortis, dolor sapien pulvinar dui, nec iaculis massa metus quis nunc. Curabitur vitae felis ut quam condimentum fermentum. Cras et laoreet nisl, eget placerat nibh. Etiam molestie velit condimentum nunc fringilla, porta posuere ex consectetur. Fusce et malesuada metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis nunc blandit, blandit tellus nec, tempor leo. Vestibulum eleifend metus orci. Morbi pretium, ipsum non accumsan lobortis, nisi ex facilisis lorem, at aliquam justo est id velit. Praesent a tempus est, in sagittis turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.'
```
Comment (xavier506) [inline hapi/src/libs/add-bps-info.js:521]: this is lorem ipsum

File: webapp/src/language/en.json [hunk 2]
```diff
@@ -227,7 +227,9 @@
     "labelTool": "votes for",
     "success" : "Success!",
     "title": "Block Producer Community Ratings for",
-    "proxyProfile": "Reviews on EOS proxy account"
+    "proxyProfile": "Reviews on EOS proxy account",
+    "edenInterview": "Eden Interview:",
```
Comment (xavier506) [inline webapp/src/language/en.json:231]: Block Producer Interview :

Comment (xavier506) [reply webapp/src/language/en.json:231]: it is not an official eden interview

**Review by xavier506 — APPROVED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM
