### PR TITLE
Fix/warnings

### LINKED ISSUE #629: General frontend warnings
Considerer next bug descriptions:
- [x] #571 
- [x] 'fade' is deprecated (see error detail below in comments)

### PR DESCRIPTION
**Pull request by leisterfrancisco**
### GH Issue

Resolves #629 

### Steps to test

1. Make run
1. Check warnings console log

### CODE REVIEW

File: webapp/src/components/input-autocomplete/index.js [hunk 1]
```diff
@@ -53,8 +53,9 @@ const InputAutocomplete = ({ ...props }) => {
   }, [list, proxies])
 
   const renderInputComponent = (inputProps) => {
-    const { inputRef = () => {}, ref, ...other } = inputProps
+    const { inputRef = () => {}, ref, classes, ...other } = inputProps
     const { hideSearchIcon, isFocused } = props
+    console.log({ other, classes })
```
Comment (leisterfrancisco) [inline webapp/src/components/input-autocomplete/index.js:58]: Is it necessary?

**Review by leisterfrancisco — COMMENTED** [review]
Nice work

**Review by AngeloCG97 — APPROVED** [review]
LGTM
