### PR TITLE
fix(webapp): apply new format to card component

### LINKED ISSUE #972: No Ratings data on homepage BPs
image

### LINKED ISSUE #974: Proxies not showing data
https://eosrate.io/proxies

image

### PR DESCRIPTION
**Pull request by hanakoori01**
### What does this PR do?

- Resolves #972 
- Resolves #974 

### Steps to test

1. Run `make run`
2. Go to `localhost:3000`
3. Go to Proxies 
4. Go to homepage

### CODE REVIEW

File: webapp/src/components/Card/index.js [hunk 1]
```diff
@@ -55,26 +55,32 @@ const CardData = ({
...
   const [open, setOpen] = useState(false)
   const classes = useStyles()
   const theme = useTheme()
   const isMobile = useMediaQuery(theme.breakpoints.only('xs'))
-
   const handleTooltip = e => {
     setOpen(!open)
     e.preventDefault()
   }
+  console.log(data)
```
Comment (tetogomez) [inline webapp/src/components/Card/index.js:70]: lol, delete this console.log

File: webapp/src/components/Card/index.js [hunk 2]
```diff
@@ -135,16 +141,9 @@ const CardData = ({
...
-                data: formatRadarData({
-                  average: data.total_average,
-                  community: data.total_community,
-                  development: data.total_development,
-                  infrastructure: data.total_infrastructure,
-                  ratings_cntr: data.total_ratings_cntr,
-                  transparency: data.total_transparency,
-                  trustiness: data.total_trustiness
-                })
+                // ...data.data,
```
Comment (tetogomez) [inline webapp/src/components/Card/index.js:144]: remove commented code

**Review by tetogomez — COMMENTED** [review]
please check the comments

**Review by tetogomez — APPROVED** [review]
LGTM
